name: Export to HTML

on:
  workflow_dispatch:  # click the button on Github repo!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install polib
    - name: Build
      run: |
        wget https://raw.githubusercontent.com/Lotus-King-Translation/Transifex-Workflow-Template/main/scripts/export_to_html.py
        mkdir -p exports
        source .languages
        python export_to_html.py $TARGET_LANGUAGE
        rm export_to_html.py
    - name: Make Commit
      run: |
        git config --global user.email mailme@mikkokotila.com
        git config --global user.name "Mikko Kotila"
        git checkout -b "export_to_html"
        git add --all
        git commit -m "Export to HTML"
    - name: Push Changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
